image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make
  script:
    - cd c
    - make
  artifacts:
    paths:
      - main
  cache:
    paths:
    - "*.o"

test:
  stage: test
  script:
    - cd c
    - make test
